/**
 * Fuentes web para scraping de trabajos de circo y artes escénicas.
 * Cada fuente define cómo acceder a sus listings.
 */

export const CIRCUS_SOURCES = [

  // ─── LINKEDIN JOBS (búsquedas públicas) ───────────────────────────────────

  {
    id: 'linkedin_circus_jobs',
    name: 'LinkedIn – Circus Performer Jobs',
    url: 'https://www.linkedin.com/jobs/search/?keywords=circus%20performer&sortBy=DD',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
    notes: 'LinkedIn tiene castings de compañías medianas y grandes',
  },
  {
    id: 'linkedin_acrobat_jobs',
    name: 'LinkedIn – Acrobat & Aerial Jobs',
    url: 'https://www.linkedin.com/jobs/search/?keywords=acrobat%20aerial%20entertainer&sortBy=DD',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
  },

  // ─── GOOGLE JOBS / AGGREGATORS ────────────────────────────────────────────

  {
    id: 'workable_circus',
    name: 'Workable – Circus & Variety',
    url: 'https://jobs.workable.com/search?query=circus+performer',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'glassdoor_performer',
    name: 'Glassdoor – Performer Jobs',
    url: 'https://www.glassdoor.com/Job/performer-jobs-SRCH_KO0,9.htm',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'ziprecruiter_circus',
    name: 'ZipRecruiter – Circus & Entertainment',
    url: 'https://www.ziprecruiter.com/jobs/search?search=circus+entertainer',
    category: 'job_board',
    language: 'en',
    region: 'america_norte',
    priority: 2,
  },
  {
    id: 'simplyhired_acrobat',
    name: 'SimplyHired – Acrobat & Aerial',
    url: 'https://www.simplyhired.com/search?q=acrobat+circus+aerial',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'talent_com_circus',
    name: 'Talent.com – Circus Jobs',
    url: 'https://www.talent.com/jobs?k=circus+performer',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'jooble_cirque',
    name: 'Jooble – Artiste Cirque',
    url: 'https://fr.jooble.org/emploi-artiste-de-cirque',
    category: 'job_board',
    language: 'fr',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'infojobs_circo',
    name: 'InfoJobs – Artista de Circo',
    url: 'https://www.infojobs.net/jobsearch/search-results/list.xhtml?keyword=circo+acrobata',
    category: 'job_board',
    language: 'es',
    region: 'europa',
    priority: 2,
    notes: 'Portal de empleo líder en España',
  },
  {
    id: 'computrabajo_circo',
    name: 'Computrabajo – Artista Circo (LATAM)',
    url: 'https://www.computrabajo.com.ar/ofertas-de-trabajo/trabajo-de-artista-de-circo',
    category: 'job_board',
    language: 'es',
    region: 'america_latina',
    priority: 2,
  },
  {
    id: 'bumeran_artista',
    name: 'Bumeran – Artista Escénico',
    url: 'https://www.bumeran.com.ar/empleos-busqueda-artista+escenico.html',
    category: 'job_board',
    language: 'es',
    region: 'america_latina',
    priority: 2,
  },
  {
    id: 'theatrejobs_uk',
    name: 'Theatre Jobs Pro (UK)',
    url: 'https://www.theatrejobspro.com/jobs/?keywords=circus',
    category: 'job_board',
    language: 'en',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'ents24_performers',
    name: 'Ents24 – Performer Jobs',
    url: 'https://www.ents24.com/uk/entertainment-jobs',
    category: 'job_board',
    language: 'en',
    region: 'europa',
    priority: 3,
  },
  {
    id: 'nycasting_circus',
    name: 'NYCasting – Circus & Variety',
    url: 'https://www.nycasting.com/jobs/?q=circus',
    category: 'job_board',
    language: 'en',
    region: 'america_norte',
    priority: 2,
  },
  {
    id: 'gigsalad_circus',
    name: 'GigSalad – Circus Performers',
    url: 'https://www.gigsalad.com/Performance_Talent/Circus_Performer',
    category: 'aggregator',
    language: 'en',
    region: 'america_norte',
    priority: 2,
    notes: 'Plataforma de contratación directa de artistas',
  },
  {
    id: 'acrobatic_world',
    name: 'Acrobatic World – Jobs',
    url: 'https://www.acrobaticworld.com/jobs',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 1,
    notes: 'Especializado en acrobacia y circo',
  },
  {
    id: 'varietyjobs',
    name: 'Variety Jobs – Entertainment',
    url: 'https://www.varietyjobs.com/search/?q=circus+acrobat+performer',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'eurojobs_performer',
    name: 'EuroJobs – Performer (Europa)',
    url: 'https://www.eurojobs.com/search-jobs/performer/',
    category: 'job_board',
    language: 'en',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'monster_circus',
    name: 'Monster.com – Circus & Acrobatics',
    url: 'https://www.monster.com/jobs/search?q=circus+acrobat&sort=date',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'polejunkie_jobs',
    name: 'Pole Junkie – Pole Aerial Jobs',
    url: 'https://polejunkie.com/jobs/',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
    notes: 'Comunidad de pole dance con ofertas de trabajo',
  },
  // danceus_jobs y iadms_jobs removidos — son plataformas de danza, no circo

  // ─── INSTAGRAM ACCOUNTS (vía link-in-bio público) ────────────────────────

  {
    id: 'circusbox_artistcards',
    name: 'Circus Box Media – Job Posts',
    url: 'https://artistcards.link/?u=circusbox',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 1,
    notes: 'Página pública de circus.box.media con listado de trabajos de circo',
  },

  // ─── JOB BOARDS PRINCIPALES ──────────────────────────────────────────────

  {
    id: 'circustalk_jobs',
    name: 'CircusTalk – Job Board',
    url: 'https://circustalk.com/circus-jobs/',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 1,
    notes: 'Mayor plataforma de empleos para artistas de circo',
  },
  {
    id: 'stagelync_circus',
    name: 'StageLync – Circus Jobs',
    url: 'https://stagelync.com/pro/jobs-and-auditions/jobs-and-auditions-for-circus-and-variety-performers',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 1,
  },
  {
    id: 'entertainers_worldwide',
    name: 'Entertainers Worldwide Jobs',
    url: 'https://www.entertainersworldwidejobs.com/circus-performer-jobs',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 1,
  },
  {
    id: 'showbizjobs_circus',
    name: 'ShowbizJobs – Circus & Variety',
    url: 'https://www.showbizjobs.com/jobs/?kw=circus',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 1,
    notes: 'Gran plataforma de empleos en entretenimiento',
  },
  {
    id: 'entertainmentcareers',
    name: 'EntertainmentCareers.net – Performers',
    url: 'https://www.entertainmentcareers.net/jobs/search/?q=circus+performer',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 1,
  },
  {
    id: 'mandy_circus',
    name: 'Mandy.com – Circus & Variety',
    url: 'https://www.mandy.com/uk/jobs/circus-variety',
    category: 'job_board',
    language: 'en',
    region: 'europa',
    priority: 1,
    notes: 'Plataforma líder en UK para artes escénicas',
  },
  {
    id: 'thestage_jobs',
    name: 'The Stage – Jobs',
    url: 'https://jobs.thestage.co.uk/jobs/?keywords=circus+acrobat',
    category: 'job_board',
    language: 'en',
    region: 'europa',
    priority: 2,
    notes: 'Publicación líder del sector escénico en UK',
  },
  {
    id: 'artsjobs_uk',
    name: 'Arts Jobs UK',
    url: 'https://www.artsjobs.org.uk/search/?category=performing-arts&sub=circus',
    category: 'job_board',
    language: 'en',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'stageagent_jobs',
    name: 'StageAgent – Auditions',
    url: 'https://stageagent.com/auditions',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'performingartsjobs',
    name: 'PerformingArtsJobs.com',
    url: 'https://performingartsjobs.com/search/?q=circus',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'playbill_jobs',
    name: 'Playbill – Jobs & Auditions',
    url: 'https://playbill.com/jobs/find?q=circus',
    category: 'job_board',
    language: 'en',
    region: 'america_norte',
    priority: 2,
  },
  {
    id: 'backstage_circus',
    name: 'Backstage – Circus Auditions',
    url: 'https://www.backstage.com/auditions/circus/',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 1,
    notes: 'Casting platform muy usada en USA',
  },
  {
    id: 'casting_networks',
    name: 'Casting Networks – Circus',
    url: 'https://app.castingnetworks.com/talent/public-auditions?search=circus',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'danse_fr',
    name: 'Danse.org – Offres',
    url: 'https://www.danse.org/les-offres-demploi/',
    category: 'job_board',
    language: 'fr',
    region: 'europa',
    priority: 2,
    notes: 'Portal francés de danza y circo',
  },
  {
    id: 'pro_acteurs',
    name: 'Pro Acteurs – Offres',
    url: 'https://www.proacteurs.com/offres-emploi?q=cirque',
    category: 'job_board',
    language: 'fr',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'artcena_fr',
    name: 'Artcena – Offres d\'emploi',
    url: 'https://www.artcena.fr/offres-emploi',
    category: 'job_board',
    language: 'fr',
    region: 'europa',
    priority: 2,
    notes: 'Centro Nacional del Circo, Teatro y Artes de Calle, Francia',
  },

  // ─── INSTITUCIONALES / FEDERACIONES ──────────────────────────────────────

  {
    id: 'fedec_opportunities',
    name: 'FEDEC – Oportunidades',
    url: 'https://www.fedec.eu/en/opportunities/',
    category: 'institutional',
    language: 'en',
    region: 'europa',
    priority: 1,
    notes: 'Federación Europea de Escuelas de Circo Profesional',
  },
  {
    id: 'circostrada',
    name: 'Circostrada Network',
    url: 'https://www.circostrada.org/en/opportunities',
    category: 'institutional',
    language: 'en',
    region: 'europa',
    priority: 1,
    notes: 'Red europea de circo contemporáneo y artes de calle',
  },
  {
    id: 'on_the_move',
    name: 'On The Move – Circus',
    url: 'https://on-the-move.org/opportunities?category=circus',
    category: 'institutional',
    language: 'en',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'circusnext',
    name: 'circusnext',
    url: 'https://circusnext.eu/calls/',
    category: 'institutional',
    language: 'en',
    region: 'europa',
    priority: 2,
    notes: 'Convocatorias para creadores emergentes de circo',
  },
  {
    id: 'ietm_opps',
    name: 'IETM – Opportunities',
    url: 'https://www.ietm.org/en/opportunities',
    category: 'institutional',
    language: 'en',
    region: 'europa',
    priority: 2,
    notes: 'Red internacional de artes escénicas contemporáneas',
  },
  {
    id: 'arts_council_england',
    name: 'Arts Council England – Jobs',
    url: 'https://www.artscouncil.org.uk/jobs',
    category: 'institutional',
    language: 'en',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'circusartsuk',
    name: 'CircusArts UK – Opportunities',
    url: 'https://www.circusarts.org.uk/opportunities',
    category: 'institutional',
    language: 'en',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'cnac_france',
    name: 'CNAC – Centre National des Arts du Cirque',
    url: 'https://www.cnac.fr/fr/formation/appels-a-candidature',
    category: 'institutional',
    language: 'fr',
    region: 'europa',
    priority: 2,
    notes: 'Escuela nacional de circo de Francia',
  },
  {
    id: 'esac_belgium',
    name: 'ESAC – École Supérieure des Arts du Cirque',
    url: 'https://www.esac.be/offres-artistiques',
    category: 'institutional',
    language: 'fr',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'inaem_spain',
    name: 'INAEM – Convocatorias (España)',
    url: 'https://www.culturaydeporte.gob.es/cultura/areascultura/artesescenicas/convocatorias-y-premios.html',
    category: 'institutional',
    language: 'es',
    region: 'europa',
    priority: 2,
    notes: 'Instituto Nacional de las Artes Escénicas y de la Música, España',
  },
  {
    id: 'iberescena',
    name: 'Iberescena – Convocatorias',
    url: 'https://programaiberescena.org/convocatorias/',
    category: 'institutional',
    language: 'es',
    region: 'global',
    priority: 2,
    notes: 'Fondo iberoamericano de apoyo a las artes escénicas',
  },

  // ─── COMPAÑÍAS Y CASTINGS ─────────────────────────────────────────────────

  {
    id: 'cirquedusoleil_casting',
    name: 'Cirque du Soleil – Casting',
    url: 'https://casting.cirquedusoleil.com/',
    category: 'company',
    language: 'en',
    region: 'global',
    priority: 1,
  },
  {
    id: 'ringling_auditions',
    name: 'Ringling Bros. – Auditions',
    url: 'https://www.feldentertainment.com/performer-auditions/ringling/',
    category: 'company',
    language: 'en',
    region: 'america_norte',
    priority: 2,
  },
  {
    id: 'circus_guide_agency',
    name: 'Circus Guide – Jobs',
    url: 'https://www.circusguideagency.com/jobs-available',
    category: 'agency',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'spiegelworld',
    name: 'Spiegelworld – Casting',
    url: 'https://spiegelworld.com/casting',
    category: 'company',
    language: 'en',
    region: 'global',
    priority: 1,
    notes: 'Productora de shows de cabaret/circo (Vegas, NYC, etc.)',
  },
  {
    id: 'seven_fingers',
    name: 'Les 7 Doigts – Casting',
    url: 'https://7fingers.com/casting',
    category: 'company',
    language: 'en',
    region: 'global',
    priority: 2,
    notes: 'Compañía de circo contemporáneo de Montreal',
  },
  {
    id: 'circa_australia',
    name: 'Circa – Contemporary Circus',
    url: 'https://www.circa.org.au/work-with-us/',
    category: 'company',
    language: 'en',
    region: 'oceania',
    priority: 2,
    notes: 'Compañía australiana de circo contemporáneo',
  },
  {
    id: 'nica_australia',
    name: 'NICA – National Institute of Circus Arts',
    url: 'https://nica.com.au/opportunities/',
    category: 'institutional',
    language: 'en',
    region: 'oceania',
    priority: 2,
  },
  {
    id: 'nofit_state',
    name: 'NoFit State Circus – Jobs',
    url: 'https://www.nofitstate.org/jobs',
    category: 'company',
    language: 'en',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'cirque_eloize',
    name: 'Cirque Éloize – Casting',
    url: 'https://www.cirque-eloize.com/en/casting',
    category: 'company',
    language: 'en',
    region: 'america_norte',
    priority: 2,
  },
  {
    id: 'new_victory_casting',
    name: 'New Victory Theater – Casting',
    url: 'https://newvictory.org/about/casting/',
    category: 'company',
    language: 'en',
    region: 'america_norte',
    priority: 3,
  },
  {
    id: 'circo_aereo',
    name: 'Circo Aereo – Open Calls',
    url: 'https://www.circoaereo.com/open-calls',
    category: 'company',
    language: 'en',
    region: 'europa',
    priority: 3,
    notes: 'Compañía finlandesa de circo',
  },

  // ─── CRUCEROS ─────────────────────────────────────────────────────────────

  {
    id: 'royal_caribbean_entertainment',
    name: 'Royal Caribbean – Entertainment',
    url: 'https://www.royalcaribbeanproductions.com/auditions',
    category: 'cruise',
    language: 'en',
    region: 'global',
    priority: 1,
  },
  {
    id: 'msc_entertainment',
    name: 'MSC Cruceros – Casting',
    url: 'https://www.msccruises.com/en-gl/msc-foundation/entertainment/casting.aspx',
    category: 'cruise',
    language: 'en',
    region: 'global',
    priority: 1,
  },
  {
    id: 'celebrity_cruises_ent',
    name: 'Celebrity Cruises – Entertainment',
    url: 'https://www.celebrity-entertainment.com/auditions',
    category: 'cruise',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'ncl_entertainment',
    name: 'Norwegian Cruise Line – Entertainment',
    url: 'https://www.ncl.com/careers/entertainment',
    category: 'cruise',
    language: 'en',
    region: 'global',
    priority: 1,
    notes: 'Norwegian tiene acróbatas y artistas en sus shows',
  },
  {
    id: 'disney_cruise_casting',
    name: 'Disney Cruise Line – Casting',
    url: 'https://disneycruiselinecastingcallonline.com',
    category: 'cruise',
    language: 'en',
    region: 'global',
    priority: 1,
  },
  {
    id: 'carnival_entertainment',
    name: 'Carnival Cruise – Entertainment Jobs',
    url: 'https://www.carnivalcorp.com/careers?category=entertainment',
    category: 'cruise',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'princess_cruises_ent',
    name: 'Princess Cruises – Entertainment',
    url: 'https://www.princess.com/en-US/careers/entertainment/',
    category: 'cruise',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'costa_cruises_ent',
    name: 'Costa Cruises – Entertainers',
    url: 'https://www.costacruises.com/careers/entertainers.html',
    category: 'cruise',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'holland_america_ent',
    name: 'Holland America – Entertainment',
    url: 'https://www.hollandamerica.com/en_US/careers/entertainment.html',
    category: 'cruise',
    language: 'en',
    region: 'global',
    priority: 3,
  },

  // ─── PARQUES TEMÁTICOS ────────────────────────────────────────────────────

  {
    id: 'disney_parks_casting',
    name: 'Disney Parks – Entertainment Casting',
    url: 'https://jobs.disneycareers.com/entertainment-auditions',
    category: 'theme_park',
    language: 'en',
    region: 'global',
    priority: 1,
    notes: 'Disney contrata acróbatas y artistas escénicos en sus parques',
  },
  {
    id: 'universal_studios_casting',
    name: 'Universal Studios – Entertainment Auditions',
    url: 'https://www.universalstudiosaustralia.com/en/entertainment/casting.html',
    category: 'theme_park',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'seaworld_ent',
    name: 'SeaWorld Entertainment – Performers',
    url: 'https://seaworld.com/careers/performer-auditions/',
    category: 'theme_park',
    language: 'en',
    region: 'america_norte',
    priority: 2,
  },
  {
    id: 'sixflags_casting',
    name: 'Six Flags – Entertainment Casting',
    url: 'https://www.sixflags.com/national/attractions/shows/casting',
    category: 'theme_park',
    language: 'en',
    region: 'america_norte',
    priority: 3,
  },

  // ─── FESTIVALES CON OPEN CALLS ────────────────────────────────────────────

  {
    id: 'festival_monte_carlo',
    name: 'Festival de Circo de Monte Carlo',
    url: 'https://www.montecarlofestival.mc/en/artists',
    category: 'festival',
    language: 'en',
    region: 'europa',
    priority: 1,
    notes: 'Festival más prestigioso del mundo (Enero)',
  },
  {
    id: 'berlin_circus_festival',
    name: 'Berlin Circus Festival – Open Call',
    url: 'https://www.berlin-circus-festival.de/artopencall.html',
    category: 'festival',
    language: 'en',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'festival_tomorrow',
    name: 'Festival Mondial du Cirque de Demain',
    url: 'https://www.festival-demain.com/open-call',
    category: 'festival',
    language: 'fr',
    region: 'europa',
    priority: 1,
    notes: 'Festival de circo más importante para artistas emergentes, París',
  },
  {
    id: 'circa_festival_australia',
    name: 'CIRCA – Brisbane Festival',
    url: 'https://brisbanefestival.com.au/circa',
    category: 'festival',
    language: 'en',
    region: 'oceania',
    priority: 2,
  },
  {
    id: 'festival_ficc',
    name: 'FICC – Festival Int. de Circo de Catalunya',
    url: 'https://www.ficc.cat/convocatoria',
    category: 'festival',
    language: 'es',
    region: 'europa',
    priority: 2,
    notes: 'Festival Internacional de Circo de Catalunya (Girona)',
  },
  {
    id: 'festival_falaises',
    name: 'Festival de Falaises – Open Call',
    url: 'https://www.festivaldefalaises.fr/appel-a-artistes',
    category: 'festival',
    language: 'fr',
    region: 'europa',
    priority: 3,
  },
  {
    id: 'awaji_art_circus',
    name: 'Awaji Art Circus (Japón)',
    url: 'https://en.awajiartscircus.com/opencall.php',
    category: 'festival',
    language: 'en',
    region: 'asia',
    priority: 2,
  },
  {
    id: 'seoul_circus_festival',
    name: 'Seoul International Circus Festival',
    url: 'https://www.seoulcircus.or.kr/en/',
    category: 'festival',
    language: 'en',
    region: 'asia',
    priority: 3,
  },
  {
    id: 'cannonball_festival',
    name: 'Cannonball Festival (USA)',
    url: 'https://www.cannonballfestival.org/opencall',
    category: 'festival',
    language: 'en',
    region: 'america_norte',
    priority: 2,
  },
  {
    id: 'festivalnet_circus',
    name: 'FestivalNet – Circus Open Calls',
    url: 'https://festivalnet.com/find/circus',
    category: 'aggregator',
    language: 'en',
    region: 'america_norte',
    priority: 2,
  },
  {
    id: 'festival_circo_montevideo',
    name: 'Festival Int. de Circo de Montevideo',
    url: 'https://www.festivalcirco.uy/convocatoria',
    category: 'festival',
    language: 'es',
    region: 'america_latina',
    priority: 2,
  },
  {
    id: 'circo_ba_festival',
    name: 'Festival de Circo Buenos Aires',
    url: 'https://www.festivaldecircoba.com/convocatoria',
    category: 'festival',
    language: 'es',
    region: 'america_latina',
    priority: 2,
  },

  // ─── AGENCIAS DE TALENTOS ─────────────────────────────────────────────────

  {
    id: 'acrobatic_arts_agency',
    name: 'Acrobatic Arts Agency – Jobs',
    url: 'https://www.acrobaticarts.com/jobs',
    category: 'agency',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'cirque_productions',
    name: 'Cirque Productions – Casting',
    url: 'https://cirqueproductions.com/casting',
    category: 'agency',
    language: 'en',
    region: 'global',
    priority: 2,
    notes: 'Agencia que produce shows para hoteles, casinos y cruceros',
  },
  {
    id: 'jkg_entertainment',
    name: 'JKG Entertainment – Casting',
    url: 'https://www.jkgentertainment.com/casting',
    category: 'agency',
    language: 'en',
    region: 'global',
    priority: 3,
  },
  {
    id: 'acro_productions',
    name: 'Acro Productions – Jobs',
    url: 'https://acroproductions.com/performers',
    category: 'agency',
    language: 'en',
    region: 'global',
    priority: 3,
  },

  // ─── LATINOAMÉRICA ────────────────────────────────────────────────────────

  {
    id: 'escuela_nacional_circo_mx',
    name: 'Escuela Nacional de Circo – México',
    url: 'https://www.enc.inba.gob.mx/convocatorias',
    category: 'institutional',
    language: 'es',
    region: 'america_latina',
    priority: 2,
  },
  {
    id: 'circo_del_sur',
    name: 'Circo del Sur – Argentina',
    url: 'https://circodelsur.com.ar/convocatorias',
    category: 'company',
    language: 'es',
    region: 'america_latina',
    priority: 2,
  },
  {
    id: 'fonca_mexico',
    name: 'FONCA – Convocatorias (México)',
    url: 'https://fonca.cultura.gob.mx/convocatorias/',
    category: 'institutional',
    language: 'es',
    region: 'america_latina',
    priority: 2,
    notes: 'Fondo Nacional para la Cultura y las Artes de México',
  },
  {
    id: 'cnca_chile',
    name: 'Ministerio de las Culturas – Convocatorias (Chile)',
    url: 'https://www.cultura.gob.cl/convocatorias/',
    category: 'institutional',
    language: 'es',
    region: 'america_latina',
    priority: 2,
  },
  {
    id: 'artegob_uruguay',
    name: 'Ministerio de Educación y Cultura – Convocatorias (Uruguay)',
    url: 'https://www.gub.uy/ministerio-educacion-cultura/tematica/artes-escenicas',
    category: 'institutional',
    language: 'es',
    region: 'america_latina',
    priority: 3,
  },
  {
    id: 'sinca_argentina',
    name: 'SINCA – Convocatorias (Argentina)',
    url: 'https://www.sinca.gob.ar/convocatorias',
    category: 'institutional',
    language: 'es',
    region: 'america_latina',
    priority: 2,
    notes: 'Sistema de Información Cultural de la Argentina',
  },
  {
    id: 'inamu_argentina',
    name: 'INAMU – Argentina',
    url: 'https://inamu.gob.ar/convocatorias/',
    category: 'institutional',
    language: 'es',
    region: 'america_latina',
    priority: 2,
  },
  {
    id: 'artescena_colombia',
    name: 'ArtEscena Colombia',
    url: 'https://artescena.com.co/convocatorias/',
    category: 'institutional',
    language: 'es',
    region: 'america_latina',
    priority: 2,
  },
  {
    id: 'circobrasil_gov',
    name: 'FUNARTE – Editais Circo (Brasil)',
    url: 'https://www.funarte.gov.br/editais/?categoria=circo',
    category: 'institutional',
    language: 'pt',
    region: 'america_latina',
    priority: 2,
    notes: 'Fundação Nacional de Artes do Brasil',
  },

  // ─── MEDIO ORIENTE / ASIA ─────────────────────────────────────────────────

  {
    id: 'ferrari_world_casting',
    name: 'Yas Theme Parks – Casting',
    url: 'https://www.yasthemeparks.com/en/careers',
    category: 'theme_park',
    language: 'en',
    region: 'medio_oriente',
    priority: 2,
    notes: 'Ferrari World, Warner Bros World, Abu Dhabi',
  },
  {
    id: 'dubai_entertainment',
    name: 'Dubai Entertainment Casting',
    url: 'https://www.dubaientertainment.com/casting',
    category: 'agency',
    language: 'en',
    region: 'medio_oriente',
    priority: 2,
  },
  {
    id: 'img_worlds',
    name: 'IMG Worlds of Adventure – Casting',
    url: 'https://www.imgworlds.com/careers',
    category: 'theme_park',
    language: 'en',
    region: 'medio_oriente',
    priority: 3,
  },

  // ─── FESTIVALES EUROPEOS CON CONVOCATORIAS ────────────────────────────────

  {
    id: 'aurillac_festival',
    name: 'Festival d\'Aurillac – Open Call',
    url: 'https://www.aurillac.net/index.php/fr/cies-de-passage/comment-sinscrire',
    category: 'festival',
    language: 'fr',
    region: 'europa',
    priority: 1,
    notes: 'Festival de teatro callejero más importante de Europa',
  },
  {
    id: 'chalon_dans_la_rue',
    name: 'Chalon dans la Rue – Artistes',
    url: 'https://www.chalondanslarue.com/artistes',
    category: 'festival',
    language: 'fr',
    region: 'europa',
    priority: 1,
  },
  {
    id: 'firatarrega_convocatoria',
    name: 'Fira Tàrrega – Convocatoria',
    url: 'https://www.firatarrega.cat/professionals',
    category: 'festival',
    language: 'es',
    region: 'europa',
    priority: 1,
    notes: 'Mercado de artes de calle más importante del sur de Europa',
  },
  {
    id: 'spancirfest_apply',
    name: 'Spancirfest – Artist Application',
    url: 'https://www.spancirfest.com/apply',
    category: 'festival',
    language: 'en',
    region: 'europa',
    priority: 1,
  },
  {
    id: 'pflasterspektakel_apply',
    name: 'Pflasterspektakel Linz – Bewerbung',
    url: 'https://www.pflasterspektakel.at/bewerbung',
    category: 'festival',
    language: 'de',
    region: 'europa',
    priority: 1,
  },
  {
    id: 'lastrada_bremen_apply',
    name: 'La Strada Bremen – Application',
    url: 'https://www.lastrada-bremen.de/kuenstler',
    category: 'festival',
    language: 'de',
    region: 'europa',
    priority: 1,
  },
  {
    id: 'mirabilia_opencall',
    name: 'Mirabilia Festival – Open Call',
    url: 'https://www.festivalmirabilia.it/open-call',
    category: 'festival',
    language: 'it',
    region: 'europa',
    priority: 1,
  },
  {
    id: 'young_stage_basel',
    name: 'Young Stage Basel – Application',
    url: 'https://www.young-stage.com/en/application',
    category: 'festival',
    language: 'en',
    region: 'europa',
    priority: 1,
    notes: 'Festival concurso de circo en Basilea, Suiza',
  },
  {
    id: 'trapezi_reus',
    name: 'Festival Trapezi – Convocatoria',
    url: 'https://www.trapezi.cat/convocatoria',
    category: 'festival',
    language: 'es',
    region: 'europa',
    priority: 1,
    notes: 'Festival circo contemporáneo Reus, España',
  },
  {
    id: 'edinburgh_fringe_performers',
    name: 'Edinburgh Festival Fringe – Performers',
    url: 'https://www.edfringe.com/take-part/perform-at-the-fringe',
    category: 'festival',
    language: 'en',
    region: 'europa',
    priority: 1,
  },
  {
    id: 'hat_fair_winchester',
    name: 'Hat Fair Winchester – Apply',
    url: 'https://www.hatfair.co.uk/apply',
    category: 'festival',
    language: 'en',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'spoffin_apply',
    name: 'Spoffin Festival – Artiest worden',
    url: 'https://www.spoffin.nl/artiesten',
    category: 'festival',
    language: 'nl',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'ana_desetnica_apply',
    name: 'Ana Desetnica Ljubljana – Application',
    url: 'https://www.anamonro.si/ana-desetnica/for-artists',
    category: 'festival',
    language: 'en',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'noorderzon_apply',
    name: 'Noorderzon Festival – Artists',
    url: 'https://www.noorderzon.nl/voor-artiesten',
    category: 'festival',
    language: 'nl',
    region: 'europa',
    priority: 1,
  },
  {
    id: 'sibiu_festival',
    name: 'Sibiu International Theatre Festival',
    url: 'https://www.sibfest.ro/en/artists',
    category: 'festival',
    language: 'en',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'world_buskers_nz',
    name: 'World Buskers Festival NZ – Apply',
    url: 'https://www.worldbuskersfestival.com/apply',
    category: 'festival',
    language: 'en',
    region: 'oceania',
    priority: 1,
    notes: 'Festival de busking más grande del hemisferio sur',
  },
  {
    id: 'artisti_in_piazza',
    name: 'Artisti in Piazza Pennabilli',
    url: 'https://www.artistiinpiazza.com/iscrizioni',
    category: 'festival',
    language: 'it',
    region: 'europa',
    priority: 2,
  },

  // ─── COMPAÑÍAS — PÁGINAS DE CASTING DIRECTAS ──────────────────────────────

  {
    id: 'cirkus_cirkor_news',
    name: 'Cirkus Cirkör — Noticias y Casting',
    url: 'https://www.cirkuscirkor.se/en/about/jobs',
    category: 'company',
    language: 'en',
    region: 'europa',
    priority: 1,
    notes: 'Compañía sueca de circo social, busca artistas con perfil comprometido',
  },
  {
    id: '7fingers_casting',
    name: 'Les 7 Doigts — Casting',
    url: 'https://7fingers.com/casting',
    category: 'company',
    language: 'fr',
    region: 'global',
    priority: 1,
    notes: 'Montreal, circo contemporáneo de alto nivel, Broadway, Netflix',
  },
  {
    id: 'eloize_casting',
    name: 'Cirque Éloize — Casting',
    url: 'https://www.cirque-eloize.com/en/company/casting',
    category: 'company',
    language: 'fr',
    region: 'global',
    priority: 1,
    notes: 'Montreal, shows en residencia y giras, estilo urbano-musical',
  },
  {
    id: 'gravity_myths_news',
    name: 'Gravity & Other Myths — Join Us',
    url: 'https://www.gravityandothermyths.com/join-us',
    category: 'company',
    language: 'en',
    region: 'global',
    priority: 1,
    notes: 'Australia, compañía muy activa en gira mundial',
  },
  {
    id: 'compagnie_xy_news',
    name: 'Compagnie XY — Actualités',
    url: 'https://www.compagnie-xy.com/actualites',
    category: 'company',
    language: 'fr',
    region: 'europa',
    priority: 1,
    notes: '23 acróbatas, acrobacia colectiva sin red, Francia',
  },
  {
    id: 'circa_australia_jobs',
    name: 'Circa Contemporary Circus — Work With Us',
    url: 'https://circa.org.au/work-with-us',
    category: 'company',
    language: 'en',
    region: 'global',
    priority: 1,
  },
  {
    id: 'fuerza_bruta_casting',
    name: 'Fuerza Bruta — Casting',
    url: 'https://www.fuerzabruta.net/casting',
    category: 'company',
    language: 'es',
    region: 'america_latina',
    priority: 1,
    notes: 'Buenos Aires, shows de inmersión 360°, giran mundialmente',
  },
  {
    id: 'dragone_jobs',
    name: 'Dragone Productions — Jobs',
    url: 'https://www.dragone.com/en/careers',
    category: 'company',
    language: 'en',
    region: 'global',
    priority: 1,
    notes: 'Shows en Vegas, Dubai, Macao, cruceros — gran formato',
  },
  {
    id: 'spiegelworld_casting',
    name: 'Spiegelworld — Casting',
    url: 'https://spiegelworld.com/casting',
    category: 'company',
    language: 'en',
    region: 'global',
    priority: 1,
    notes: 'Vegas, NYC, Australia — varieté adulto, muy activos en casting',
  },
  {
    id: 'finzi_pasca_news',
    name: 'Compagnia Finzi Pasca — News',
    url: 'https://www.finzipasca.com/en/news',
    category: 'company',
    language: 'fr',
    region: 'global',
    priority: 2,
    notes: 'Suiza, circo teatro, Olimpiadas, Cirque du Soleil',
  },
  {
    id: 'extraordinary_bodies_casting',
    name: 'Extraordinary Bodies — Casting',
    url: 'https://www.extraordinarybodies.co.uk/get-involved',
    category: 'company',
    language: 'en',
    region: 'europa',
    priority: 2,
    notes: 'Circo inclusivo UK, artistas con y sin discapacidad',
  },

  // ─── CIRCOSTRADA Y REDES EUROPEAS ─────────────────────────────────────────
  {
    id: 'circostrada_calls',
    name: 'Circostrada — Calls & Opportunities',
    url: 'https://www.circostrada.org/en/opportunities',
    category: 'network',
    language: 'en',
    region: 'europa',
    priority: 1,
    notes: 'Red europea, agrega residencias, financiaciones y convocatorias de +100 organizaciones',
  },
  {
    id: 'circusinfo_auditions',
    name: 'CircusInfo — Auditions',
    url: 'https://www.circusinfo.net/auditions',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 1,
    notes: 'Directorio global del sector circense, convocatorias internacionales',
  },

  // ─── CRUCEROS — LÍNEAS FALTANTES ──────────────────────────────────────────

  {
    id: 'viking_ocean_entertainment',
    name: 'Viking Ocean Cruises — Entertainment Jobs',
    url: 'https://www.vikingcruises.com/careers/entertainment-jobs.html',
    category: 'cruise',
    language: 'en',
    region: 'global',
    priority: 2,
    notes: 'Línea de lujo europea con shows en vivo',
  },
  {
    id: 'silversea_casting',
    name: 'Silversea Cruises — Entertainment Casting',
    url: 'https://www.silversea.com/careers/onboard-jobs/entertainment.html',
    category: 'cruise',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'azamara_entertainment',
    name: 'Azamara — Entertainment Careers',
    url: 'https://www.azamara.com/en/about/careers',
    category: 'cruise',
    language: 'en',
    region: 'global',
    priority: 3,
  },
  {
    id: 'oceania_cruises_ent',
    name: 'Oceania Cruises — Entertainment',
    url: 'https://www.oceaniacruises.com/careers/entertainment',
    category: 'cruise',
    language: 'en',
    region: 'global',
    priority: 3,
  },
  {
    id: 'cunard_entertainment',
    name: 'Cunard — Entertainment Performers',
    url: 'https://www.cunard.com/en-gb/careers/onboard-careers/entertainment',
    category: 'cruise',
    language: 'en',
    region: 'global',
    priority: 2,
    notes: 'Queen Mary 2, Queen Victoria, Queen Elizabeth',
  },
  {
    id: 'tui_cruises_ent',
    name: 'TUI Cruises — Entertainment Casting',
    url: 'https://www.tuicruises.com/jobs/entertainment',
    category: 'cruise',
    language: 'de',
    region: 'global',
    priority: 2,
    notes: 'Cruceros alemanes, activos en casting de entertainers',
  },
  {
    id: 'aida_entertainment',
    name: 'AIDA Cruises — Entertainment',
    url: 'https://www.aida.de/karriere/jobs-an-bord.html',
    category: 'cruise',
    language: 'de',
    region: 'global',
    priority: 2,
  },

  // ─── MAGIA Y MALABARES ────────────────────────────────────────────────────

  {
    id: 'ija_jobs',
    name: 'IJA — International Jugglers Association Jobs',
    url: 'https://juggle.org/jobs/',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 1,
    notes: 'Única bolsa de trabajo especializada en malabares',
  },
  {
    id: 'magic_junction_jobs',
    name: 'Magic Junction — Jobs for Magicians',
    url: 'https://www.magicjunction.com/jobs',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'magicgigs',
    name: 'MagicGigs — Bookings & Jobs',
    url: 'https://www.magicgigs.com/jobs',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'fism_competitions',
    name: 'FISM — Competitions & Events',
    url: 'https://www.fism.net/competitions',
    category: 'institutional',
    language: 'en',
    region: 'global',
    priority: 2,
    notes: 'Federación Internacional de Sociedades de Magia, olympiad cada 3 años',
  },
  {
    id: 'saldomago_convocatorias',
    name: 'Saldo Mago — Convocatorias',
    url: 'https://saldomago.com/convocatorias',
    category: 'job_board',
    language: 'es',
    region: 'america_latina',
    priority: 2,
    notes: 'Comunidad de magos hispanohablantes',
  },

  // ─── BUSKING / ARTES DE CALLE ─────────────────────────────────────────────

  {
    id: 'streetwise_buskers',
    name: 'StreetWise Buskers — Directory & Jobs',
    url: 'https://www.streetwisebuskers.com/jobs',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'busk_in_london',
    name: 'Busk in London — Auditions',
    url: 'https://www.buskinlondon.com/auditions',
    category: 'institutional',
    language: 'en',
    region: 'europa',
    priority: 2,
    notes: 'Programa oficial del metro de Londres',
  },
  {
    id: 'covent_garden_busking',
    name: 'Covent Garden — Busking Applications',
    url: 'https://www.coventgarden.london/about/busking',
    category: 'institutional',
    language: 'en',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'festival_mondial_buskers',
    name: 'Festival Mondial des Artistes de Rue',
    url: 'https://www.festivalmondial.com/candidature',
    category: 'festival',
    language: 'fr',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'perth_buskers_world',
    name: 'Perth Buskers World — Application',
    url: 'https://www.perthbuskersfestival.com.au/apply',
    category: 'festival',
    language: 'en',
    region: 'oceania',
    priority: 2,
  },

  // ─── LATINOAMÉRICA — COBERTURA ADICIONAL ──────────────────────────────────

  {
    id: 'mincultura_colombia',
    name: 'MinCulturas Colombia — Convocatorias',
    url: 'https://mincultura.gov.co/areas/artes/convocatorias',
    category: 'institutional',
    language: 'es',
    region: 'america_latina',
    priority: 2,
    notes: 'Ministerio de Culturas de Colombia',
  },
  {
    id: 'cultura_peru',
    name: 'Ministerio de Cultura Perú — Convocatorias',
    url: 'https://www.gob.pe/institucion/cultura/convocatorias',
    category: 'institutional',
    language: 'es',
    region: 'america_latina',
    priority: 2,
  },
  {
    id: 'circobrasil_comunidade',
    name: 'Circobrasil — Oportunidades',
    url: 'https://www.circobrasil.com.br/oportunidades',
    category: 'job_board',
    language: 'pt',
    region: 'america_latina',
    priority: 1,
    notes: 'Mayor portal de circo de Brasil',
  },
  {
    id: 'diadecirco_br',
    name: 'Dia de Circo — Oportunidades (Brasil)',
    url: 'https://www.diadecirco.com.br/oportunidades',
    category: 'job_board',
    language: 'pt',
    region: 'america_latina',
    priority: 2,
  },
  {
    id: 'artelatino_convocatorias',
    name: 'Arte Latino — Convocatorias',
    url: 'https://www.artelatino.com/convocatorias',
    category: 'aggregator',
    language: 'es',
    region: 'america_latina',
    priority: 2,
    notes: 'Agregador de convocatorias para artes escénicas en LATAM',
  },
  {
    id: 'cultura_ec_convocatorias',
    name: 'Ministerio de Cultura Ecuador',
    url: 'https://www.culturaypatrimonio.gob.ec/convocatorias',
    category: 'institutional',
    language: 'es',
    region: 'america_latina',
    priority: 3,
  },
  {
    id: 'circo_venezuela',
    name: 'Circo Venezuela — Casting',
    url: 'https://www.circovenezuela.org/casting',
    category: 'company',
    language: 'es',
    region: 'america_latina',
    priority: 3,
  },

  // ─── INDIA Y ASIA ─────────────────────────────────────────────────────────

  {
    id: 'great_indian_circus',
    name: 'Great Indian Circus — Auditions',
    url: 'https://www.greatindiancircus.com/auditions',
    category: 'company',
    language: 'en',
    region: 'asia',
    priority: 3,
    notes: 'Mayor compañía de circo de la India',
  },
  {
    id: 'china_arts_jobs',
    name: 'China International Arts Festival — Calls',
    url: 'https://www.cnticiaf.org/en/calls',
    category: 'institutional',
    language: 'en',
    region: 'asia',
    priority: 2,
  },
  {
    id: 'japan_stage_jobs',
    name: 'Stage Jobs Japan',
    url: 'https://www.stagejobsjapan.com/?q=circus',
    category: 'job_board',
    language: 'en',
    region: 'asia',
    priority: 2,
  },

  // ─── RESIDENCIAS ARTÍSTICAS ───────────────────────────────────────────────

  {
    id: 'resartis_circus',
    name: 'Res Artis — Residencias de Circo',
    url: 'https://www.resartis.org/residencies/?discipline=circus',
    category: 'institutional',
    language: 'en',
    region: 'global',
    priority: 2,
    notes: 'Red global de residencias artísticas, filtro por circo',
  },
  {
    id: 'transartists_circus',
    name: 'TransArtists — Residencias',
    url: 'https://www.transartists.org/residencies?discipline=performing_arts',
    category: 'institutional',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'la_central_casting',
    name: 'La Central del Circ — Residencias (Barcelona)',
    url: 'https://www.lacentraldelcirc.cat/convocatories',
    category: 'institutional',
    language: 'es',
    region: 'europa',
    priority: 1,
    notes: 'Centro de creación de circo contemporáneo de Barcelona',
  },
  {
    id: 'akademie_fuer_zirkus',
    name: 'Akademie für Circus & Performance Art',
    url: 'https://www.zirkus-akademie.net/ausschreibungen',
    category: 'institutional',
    language: 'de',
    region: 'europa',
    priority: 2,
    notes: 'Alemania, convocatorias de residencias y becas',
  },

  // ─── JOB BOARDS GENÉRICOS CON BÚSQUEDAS ÚTILES ───────────────────────────

  {
    id: 'indeed_circus_global',
    name: 'Indeed — Circus Performer (Global)',
    url: 'https://www.indeed.com/jobs?q=circus+performer&sort=date',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'indeed_acrobat',
    name: 'Indeed — Acrobat & Aerial',
    url: 'https://www.indeed.com/jobs?q=acrobat+aerial+performer&sort=date',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'indeed_artista_circo_es',
    name: 'Indeed — Artista Circo (España)',
    url: 'https://es.indeed.com/jobs?q=artista+circo+acrobata&sort=date',
    category: 'job_board',
    language: 'es',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'indeed_artista_latam',
    name: 'Indeed — Artista Escénico (LATAM)',
    url: 'https://www.indeed.com.ar/jobs?q=artista+escenico+circo&sort=date',
    category: 'job_board',
    language: 'es',
    region: 'america_latina',
    priority: 2,
  },
  {
    id: 'indeed_cirque_fr',
    name: 'Indeed — Artiste Cirque (Francia)',
    url: 'https://fr.indeed.com/jobs?q=artiste+cirque+acrobate&sort=date',
    category: 'job_board',
    language: 'fr',
    region: 'europa',
    priority: 2,
  },
  {
    id: 'linkedin_cruise_entertainer',
    name: 'LinkedIn — Cruise Ship Entertainer',
    url: 'https://www.linkedin.com/jobs/search/?keywords=cruise+ship+entertainer+performer&sortBy=DD',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 2,
  },
  {
    id: 'linkedin_street_performer',
    name: 'LinkedIn — Street Performer & Variety',
    url: 'https://www.linkedin.com/jobs/search/?keywords=street+performer+variety+juggler&sortBy=DD',
    category: 'job_board',
    language: 'en',
    region: 'global',
    priority: 3,
  },

];

// Canales públicos de Telegram — verificados o con alta probabilidad de existir
export const TELEGRAM_CHANNELS = [
  // Confirmados en búsqueda
  { handle: 'castingsdiarios',       name: 'Castings Diarios',              lang: 'es', region: 'america_latina' },
  { handle: 'CastingArg',            name: 'Argentina Casting',             lang: 'es', region: 'america_latina' },
  { handle: 'castinglatinas',        name: 'Casting Latinas',               lang: 'es', region: 'america_latina' },
  { handle: 'STAYCIRCUS',            name: 'Stay Circus',                   lang: 'en', region: 'global' },

  // Artes escénicas y circo — candidatos a verificar
  { handle: 'circoempleos',          name: 'Circo Empleos',                 lang: 'es', region: 'global' },
  { handle: 'castingcirco',          name: 'Casting Circo',                 lang: 'es', region: 'global' },
  { handle: 'circusjobsboard',       name: 'Circus Jobs Board',             lang: 'en', region: 'global' },
  { handle: 'circuscastings',        name: 'Circus Castings',               lang: 'en', region: 'global' },
  { handle: 'cruiseshipjobs',        name: 'Cruise Ship Jobs',              lang: 'en', region: 'global' },
  { handle: 'circobrasil',           name: 'Circo Brasil',                  lang: 'pt', region: 'america_latina' },
  { handle: 'circusperformerjobs',   name: 'Circus Performer Jobs',         lang: 'en', region: 'global' },
  { handle: 'acrobatjobs',           name: 'Acrobat Jobs',                  lang: 'en', region: 'global' },
  { handle: 'artesescenicas_latam',  name: 'Artes Escénicas LATAM',         lang: 'es', region: 'america_latina' },
  { handle: 'castingcolombia',       name: 'Casting Colombia',              lang: 'es', region: 'america_latina' },
  { handle: 'castingmexico',         name: 'Casting México',                lang: 'es', region: 'america_latina' },
  { handle: 'castingchile',          name: 'Casting Chile',                 lang: 'es', region: 'america_latina' },
  { handle: 'teatroemprego_br',      name: 'Teatro e Emprego Brasil',       lang: 'pt', region: 'america_latina' },
  { handle: 'circuseurope',          name: 'Circus Europe',                 lang: 'en', region: 'europa' },
  { handle: 'artdujob',             name: 'Art du Job (France)',            lang: 'fr', region: 'europa' },
  { handle: 'emploispectacle',       name: 'Emploi Spectacle',              lang: 'fr', region: 'europa' },
  { handle: 'entertainerjobs',       name: 'Entertainer Jobs',              lang: 'en', region: 'global' },
  { handle: 'cruiseentertainment',   name: 'Cruise Entertainment Jobs',     lang: 'en', region: 'global' },
  { handle: 'resortentertainment',   name: 'Resort & Hotel Entertainment',  lang: 'en', region: 'global' },
  { handle: 'themepark_jobs',        name: 'Theme Park Performer Jobs',     lang: 'en', region: 'global' },
  { handle: 'juggling_jobs',         name: 'Juggling Jobs',                 lang: 'en', region: 'global' },
  { handle: 'magic_gigs',            name: 'Magic Gigs & Jobs',             lang: 'en', region: 'global' },
];
